// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbWGvhwXtQwuAeVKU8AXh9RrLVZAIh8U0',
    appId: '1:548210284023:web:e16617495da3f126f8caf2',
    messagingSenderId: '548210284023',
    projectId: 'lotusgems-1ed4f',
    authDomain: 'lotusgems-1ed4f.firebaseapp.com',
    storageBucket: 'lotusgems-1ed4f.firebasestorage.app',
    measurementId: 'G-0346HBCJCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeAebfXJZ_gYpNRK9WO7DvgwxuQURRp3s',
    appId: '1:548210284023:android:c0c98e5bf083eb3af8caf2',
    messagingSenderId: '548210284023',
    projectId: 'lotusgems-1ed4f',
    storageBucket: 'lotusgems-1ed4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhEvrgOXBKAadDB69XHFAY5981HKCnSHk',
    appId: '1:548210284023:ios:35fb8dd9075b0569f8caf2',
    messagingSenderId: '548210284023',
    projectId: 'lotusgems-1ed4f',
    storageBucket: 'lotusgems-1ed4f.firebasestorage.app',
    iosBundleId: 'com.example.lotusandgems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhEvrgOXBKAadDB69XHFAY5981HKCnSHk',
    appId: '1:548210284023:ios:35fb8dd9075b0569f8caf2',
    messagingSenderId: '548210284023',
    projectId: 'lotusgems-1ed4f',
    storageBucket: 'lotusgems-1ed4f.firebasestorage.app',
    iosBundleId: 'com.example.lotusandgems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbWGvhwXtQwuAeVKU8AXh9RrLVZAIh8U0',
    appId: '1:548210284023:web:b35da89115999b17f8caf2',
    messagingSenderId: '548210284023',
    projectId: 'lotusgems-1ed4f',
    authDomain: 'lotusgems-1ed4f.firebaseapp.com',
    storageBucket: 'lotusgems-1ed4f.firebasestorage.app',
    measurementId: 'G-NBW4SWTKKG',
  );
}
